{{- if .Values.aeterna.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aeterna.serviceAccountName" . }}
  labels:
    {{- include "aeterna.labels" . | nindent 4 }}
  {{- $saAnns := default dict .Values.aeterna.serviceAccount.annotations }}
  {{- if and (eq .Values.kms.provider "aws") (eq .Values.kms.aws.auth "irsa") .Values.kms.aws.roleArn }}
  {{- $saAnns = merge (dict "eks.amazonaws.com/role-arn" .Values.kms.aws.roleArn) $saAnns }}
  {{- end }}
  {{- if $saAnns }}
  annotations:
    {{- toYaml $saAnns | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.aeterna.serviceAccount.automount }}
{{- end }}