use std::collections::HashMap;

pub const ALL_ACTIONS: &[&str] = &[
    "ViewMemory",
    "CreateMemory",
    "UpdateMemory",
    "DeleteMemory",
    "PromoteMemory",
    "SearchMemory",
    "ListMemory",
    "OptimizeMemory",
    "ReasonMemory",
    "CloseMemory",
    "FeedbackMemory",
    "ViewKnowledge",
    "ProposeKnowledge",
    "EditKnowledge",
    "ApproveKnowledge",
    "DeprecateKnowledge",
    "ListKnowledge",
    "SearchKnowledge",
    "BatchKnowledge",
    "ViewPolicy",
    "CreatePolicy",
    "EditPolicy",
    "ApprovePolicy",
    "SimulatePolicy",
    "ViewGovernanceRequest",
    "SubmitGovernanceRequest",
    "ApproveGovernanceRequest",
    "RejectGovernanceRequest",
    "ViewOrganization",
    "CreateOrganization",
    "CreateTeam",
    "CreateProject",
    "ManageMembers",
    "AssignRoles",
    "RegisterAgent",
    "RevokeAgent",
    "DelegateToAgent",
    "ViewAuditLog",
    "ExportData",
    "ImportData",
    "ConfigureGovernance",
    "ListTenants",
    "CreateTenant",
    "ViewTenant",
    "UpdateTenant",
    "DeactivateTenant",
    "ViewTenantConfig",
    "UpdateTenantConfig",
    "ManageTenantSecrets",
    "ViewRepositoryBinding",
    "UpdateRepositoryBinding",
    "ManageGitProviderConnections",
    "ViewGitProviderConnections",
    "CreateSession",
    "ViewSession",
    "EndSession",
    "TriggerSync",
    "ViewSyncStatus",
    "ResolveConflict",
    "QueryGraph",
    "ModifyGraph",
    "InvokeCCA",
    "InvokeMcpTool",
    "ViewUser",
    "RegisterUser",
    "UpdateUser",
    "DeactivateUser",
    "AdminSyncGitHub",
];

pub fn role_permission_matrix() -> HashMap<String, Vec<String>> {
    let platform_admin: Vec<&str> = ALL_ACTIONS.to_vec();

    let tenant_admin: Vec<&str> = ALL_ACTIONS
        .iter()
        .copied()
        .filter(|a| {
            !matches!(
                *a,
                "ListTenants" | "CreateTenant" | "ManageGitProviderConnections" | "AdminSyncGitHub"
            )
        })
        .collect();

    let admin: Vec<&str> = tenant_admin.clone();

    let architect: Vec<&str> = vec![
        "ViewMemory",
        "CreateMemory",
        "UpdateMemory",
        "DeleteMemory",
        "PromoteMemory",
        "SearchMemory",
        "ListMemory",
        "OptimizeMemory",
        "ReasonMemory",
        "CloseMemory",
        "FeedbackMemory",
        "ViewKnowledge",
        "ProposeKnowledge",
        "EditKnowledge",
        "ApproveKnowledge",
        "DeprecateKnowledge",
        "ListKnowledge",
        "SearchKnowledge",
        "BatchKnowledge",
        "ViewPolicy",
        "CreatePolicy",
        "EditPolicy",
        "ApprovePolicy",
        "SimulatePolicy",
        "ViewGovernanceRequest",
        "SubmitGovernanceRequest",
        "ApproveGovernanceRequest",
        "RejectGovernanceRequest",
        "ViewOrganization",
        "CreateTeam",
        "CreateProject",
        "ManageMembers",
        "RegisterAgent",
        "RevokeAgent",
        "DelegateToAgent",
        "ViewAuditLog",
        "ViewTenant",
        "ViewTenantConfig",
        "ViewGitProviderConnections",
        "ViewRepositoryBinding",
        "CreateSession",
        "ViewSession",
        "EndSession",
        "TriggerSync",
        "ViewSyncStatus",
        "ResolveConflict",
        "QueryGraph",
        "ModifyGraph",
        "InvokeCCA",
        "InvokeMcpTool",
        "ViewUser",
    ];

    let tech_lead: Vec<&str> = vec![
        "ViewMemory",
        "CreateMemory",
        "UpdateMemory",
        "DeleteMemory",
        "PromoteMemory",
        "SearchMemory",
        "ListMemory",
        "OptimizeMemory",
        "ReasonMemory",
        "CloseMemory",
        "FeedbackMemory",
        "ViewKnowledge",
        "ProposeKnowledge",
        "EditKnowledge",
        "ApproveKnowledge",
        "DeprecateKnowledge",
        "ListKnowledge",
        "SearchKnowledge",
        "BatchKnowledge",
        "ViewPolicy",
        "CreatePolicy",
        "SimulatePolicy",
        "ViewGovernanceRequest",
        "SubmitGovernanceRequest",
        "ApproveGovernanceRequest",
        "RejectGovernanceRequest",
        "ViewOrganization",
        "CreateProject",
        "ManageMembers",
        "RegisterAgent",
        "RevokeAgent",
        "DelegateToAgent",
        "ViewAuditLog",
        "ViewTenant",
        "ViewTenantConfig",
        "ViewRepositoryBinding",
        "ViewGitProviderConnections",
        "CreateSession",
        "ViewSession",
        "EndSession",
        "TriggerSync",
        "ViewSyncStatus",
        "QueryGraph",
        "ModifyGraph",
        "InvokeCCA",
        "InvokeMcpTool",
        "ViewUser",
    ];

    let developer: Vec<&str> = vec![
        "ViewMemory",
        "CreateMemory",
        "UpdateMemory",
        "SearchMemory",
        "ListMemory",
        "FeedbackMemory",
        "ViewKnowledge",
        "ProposeKnowledge",
        "ListKnowledge",
        "SearchKnowledge",
        "ViewPolicy",
        "SimulatePolicy",
        "ViewGovernanceRequest",
        "SubmitGovernanceRequest",
        "ViewOrganization",
        "RegisterAgent",
        "DelegateToAgent",
        "CreateSession",
        "ViewSession",
        "EndSession",
        "ViewSyncStatus",
        "QueryGraph",
        "InvokeCCA",
        "InvokeMcpTool",
        "ViewTenant",
        "ViewTenantConfig",
        "ViewRepositoryBinding",
        "ViewGitProviderConnections",
        "ViewUser",
    ];

    let viewer: Vec<&str> = vec![
        "ViewMemory",
        "SearchMemory",
        "ListMemory",
        "ViewKnowledge",
        "ListKnowledge",
        "SearchKnowledge",
        "ViewPolicy",
        "SimulatePolicy",
        "ViewGovernanceRequest",
        "ViewOrganization",
        "ViewSyncStatus",
        "ViewSession",
        "ViewTenant",
        "ViewTenantConfig",
        "ViewRepositoryBinding",
        "ViewGitProviderConnections",
        "QueryGraph",
        "ViewUser",
    ];

    let mut map: HashMap<String, Vec<String>> = HashMap::new();
    map.insert(
        "platformAdmin".to_string(),
        platform_admin.iter().map(|s| s.to_string()).collect(),
    );
    map.insert(
        "tenantAdmin".to_string(),
        tenant_admin.iter().map(|s| s.to_string()).collect(),
    );
    map.insert(
        "admin".to_string(),
        admin.iter().map(|s| s.to_string()).collect(),
    );
    map.insert(
        "architect".to_string(),
        architect.iter().map(|s| s.to_string()).collect(),
    );
    map.insert(
        "techLead".to_string(),
        tech_lead.iter().map(|s| s.to_string()).collect(),
    );
    map.insert(
        "developer".to_string(),
        developer.iter().map(|s| s.to_string()).collect(),
    );
    map.insert(
        "viewer".to_string(),
        viewer.iter().map(|s| s.to_string()).collect(),
    );
    map
}
