#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE="${SCRIPT_DIR}/../docs/security/rbac-matrix.md"

generate_matrix() {
    cat << 'EOF'
# RBAC Permission Matrix

Generated by `scripts/generate_rbac_matrix.sh`

## Role Hierarchy

| Precedence | Role | Description |
|------------|------|-------------|
| 4 | Admin | Full system access |
| 3 | Architect | Knowledge management, approvals |
| 2 | TechLead | Team management, promotions |
| 1 | Developer | Basic access, user-layer editing |
| 0 | Agent | Minimal delegated access |

## Permission Matrix

### Memory Resources

| Action | Agent | Developer | TechLead | Architect | Admin |
|--------|-------|-----------|----------|-----------|-------|
| View | ✅ | ✅ | ✅ | ✅ | ✅ |
| Create (user-layer) | ❌ | ✅ | ✅ | ✅ | ✅ |
| Create (team-layer) | ❌ | ❌ | ✅ | ✅ | ✅ |
| Edit (user-layer) | ❌ | ✅ | ✅ | ✅ | ✅ |
| Edit (team-layer) | ❌ | ❌ | ✅ | ✅ | ✅ |
| Delete | ❌ | ❌ | ❌ | ❌ | ✅ |
| Promote (team) | ❌ | ❌ | ✅ | ✅ | ✅ |
| Promote (org) | ❌ | ❌ | ❌ | ✅ | ✅ |

### Knowledge Resources

| Action | Agent | Developer | TechLead | Architect | Admin |
|--------|-------|-----------|----------|-----------|-------|
| View | ✅ | ✅ | ✅ | ✅ | ✅ |
| Create | ❌ | ❌ | ❌ | ✅ | ✅ |
| Edit | ❌ | ❌ | ❌ | ✅ | ✅ |
| Delete (draft) | ❌ | ❌ | ❌ | ✅ | ✅ |
| Approve | ❌ | ❌ | ❌ | ✅ | ✅ |

### Governance Resources

| Action | Agent | Developer | TechLead | Architect | Admin |
|--------|-------|-----------|----------|-----------|-------|
| View Events | ❌ | ❌ | ❌ | ❌ | ✅ |
| Approve Events | ❌ | ❌ | ❌ | ❌ | ✅ |

### Unit Administration

| Action | Agent | Developer | TechLead | Architect | Admin |
|--------|-------|-----------|----------|-----------|-------|
| Admin | ❌ | ❌ | ❌ | ❌ | ✅ |
| ManageRoles | ❌ | ❌ | ❌ | ❌ | ✅ |

## Agent Delegation (ActAs)

Agents can only perform actions that:
1. The delegating user has permission for
2. The agent has an explicit ActAs policy for that user

```
Agent permissions = ActAs(user) ∩ User permissions
```

## Cedar Policy Reference

See `adapters/tests/rbac_matrix_test.rs` for comprehensive authorization tests.

## Verification

Run RBAC tests:
```bash
cargo test -p adapters --test rbac_matrix_test
cargo test -p adapters --test cedar_integration
```

## Last Updated

$(date -u +"%Y-%m-%d %H:%M UTC")
EOF
}

mkdir -p "$(dirname "$OUTPUT_FILE")"
generate_matrix > "$OUTPUT_FILE"

echo "Generated RBAC matrix: $OUTPUT_FILE"
