apiVersion: v1
kind: Namespace
metadata:
  name: aeterna-qdrant
  labels:
    app.kubernetes.io/part-of: aeterna
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qdrant-config
  namespace: aeterna-qdrant
data:
  config.yaml: |
    cluster:
      enabled: true
      p2p:
        port: 6335
      consensus:
        tick_period_ms: 100
    storage:
      storage_path: /qdrant/storage
      snapshots_path: /qdrant/snapshots
      optimizers:
        default_segment_number: 2
        memmap_threshold_kb: 20000
        indexing_threshold_kb: 20000
      performance:
        max_search_threads: 0
        max_optimization_threads: 2
    service:
      grpc_port: 6334
      http_port: 6333
      enable_tls: true
      verify_https_client_certificate: true
    tls:
      cert: /etc/qdrant/tls/tls.crt
      key: /etc/qdrant/tls/tls.key
      ca_cert: /etc/qdrant/tls/ca.crt
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-headless
  namespace: aeterna-qdrant
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/part-of: aeterna
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
    - name: grpc
      port: 6334
      targetPort: 6334
    - name: p2p
      port: 6335
      targetPort: 6335
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: aeterna-qdrant
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/part-of: aeterna
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
    - name: grpc
      port: 6334
      targetPort: 6334
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: aeterna-qdrant
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/part-of: aeterna
spec:
  serviceName: qdrant-headless
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/name: qdrant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qdrant
        app.kubernetes.io/part-of: aeterna
    spec:
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: qdrant
              topologyKey: topology.kubernetes.io/zone
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.12.4
          ports:
            - containerPort: 6333
              name: http
            - containerPort: 6334
              name: grpc
            - containerPort: 6335
              name: p2p
          env:
            - name: QDRANT__CLUSTER__ENABLED
              value: "true"
            - name: QDRANT__CLUSTER__P2P__PORT
              value: "6335"
            - name: QDRANT__SERVICE__HTTP_PORT
              value: "6333"
            - name: QDRANT__SERVICE__GRPC_PORT
              value: "6334"
          args:
            - "--config-path"
            - "/qdrant/config/config.yaml"
            - "--uri"
            - "http://qdrant-0.qdrant-headless.aeterna-qdrant.svc.cluster.local:6335"
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
            - name: qdrant-snapshots
              mountPath: /qdrant/snapshots
            - name: qdrant-config
              mountPath: /qdrant/config
            - name: qdrant-tls
              mountPath: /etc/qdrant/tls
              readOnly: true
          resources:
            requests:
              cpu: "1"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 8Gi
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6333
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /livez
              port: 6333
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
      volumes:
        - name: qdrant-config
          configMap:
            name: qdrant-config
        - name: qdrant-tls
          secret:
            secretName: qdrant-tls
  volumeClaimTemplates:
    - metadata:
        name: qdrant-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3-encrypted
        resources:
          requests:
            storage: 50Gi
    - metadata:
        name: qdrant-snapshots
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3-encrypted
        resources:
          requests:
            storage: 50Gi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: qdrant-pdb
  namespace: aeterna-qdrant
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: qdrant
