pub const AETERNA_TENANT_ID: &str = "AETERNA_TENANT_ID";
pub const AETERNA_K8S_NAMESPACE: &str = "AETERNA_K8S_NAMESPACE";
pub const AETERNA_AUTH_BACKEND: &str = "AETERNA_AUTH_BACKEND";
pub const AETERNA_DEFAULT_TENANT_ID: &str = "AETERNA_DEFAULT_TENANT_ID";
